version: '2'
services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - /opt/docker-compose-mongodb:/vagas
    links:
      - db:mongodb
    container_name: vagas
    depends_on:
      - db
  db:
    image: mongo:3.0.2
    container_name: vagas_db